global:
  scrape_interval: 5s  # How frequently Prometheus scrapes metrics

scrape_configs:
  - job_name: eureka-discovery
    eureka_sd_configs:
    - server: http://host.docker.internal:8081/eureka

    relabel_configs:
    - source_labels: [__meta_eureka_app_instance_metadata_prometheus_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_service]
      target_label: service
    - source_labels: [__meta_instance]
      target_label: instance
    - source_labels: [__meta_port]
      target_label: port
